export const browserCoreExamples = [
  "freeclaw browser status",
  "freeclaw browser start",
  "freeclaw browser stop",
  "freeclaw browser tabs",
  "freeclaw browser open https://example.com",
  "freeclaw browser focus abcd1234",
  "freeclaw browser close abcd1234",
  "freeclaw browser screenshot",
  "freeclaw browser screenshot --full-page",
  "freeclaw browser screenshot --ref 12",
  "freeclaw browser snapshot",
  "freeclaw browser snapshot --format aria --limit 200",
  "freeclaw browser snapshot --efficient",
  "freeclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "freeclaw browser navigate https://example.com",
  "freeclaw browser resize 1280 720",
  "freeclaw browser click 12 --double",
  'freeclaw browser type 23 "hello" --submit',
  "freeclaw browser press Enter",
  "freeclaw browser hover 44",
  "freeclaw browser drag 10 11",
  "freeclaw browser select 9 OptionA OptionB",
  "freeclaw browser upload /tmp/file.pdf",
  'freeclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "freeclaw browser dialog --accept",
  'freeclaw browser wait --text "Done"',
  "freeclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "freeclaw browser console --level error",
  "freeclaw browser pdf",
];
